on:
  pull_request:
    branches:
      - master

name: rubocop

jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: gimenete/rubocop-action@1.0
      - name: Rubocop checks
        env:
          GITHUB_TOKEN: ${{ secrets.RUBOCOP_SECRET }}
        run: rubocop
