name: Rubocop
on:
  pull_request:
    branches:
      - master

jobs:
  rubocop:
    name: Rubocop Action
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@v2.0.1
      with:
        version: '0.74.0'
        additional_gems: 'rubocop-rails rubocop-performance rubocop-rspec' 
        fail_level: 'warning'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
