on:
  pull_request:
    branches:
      - master

name: rubocop

jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Rubocop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
