name: Rubocop
on: [push]

jobs:
  rubocop:
    name: Rubocop Action
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@v3.0.0.rc1
      with:
        action_config_path: '.github/config/rubocop_linter_action.yml'

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
